/* Leo's photo, shared by the hero pill and the dialog it opens. */
export const BOSS_URL = 'https://storage.procd.cc/leo.jpg';
export const BOSS_BLUR =
  'data:image/jpeg;base64,/9j/2wBDAA0JCgsKCA0LCgsODg0PEyAVExISEyccHhcgLikxMC4pLSwzOko+MzZGNywtQFdBRkxOUlNSMj5aYVpQYEpRUk//2wBDAQ4ODhMREyYVFSZPNS01T09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0//wAARCAAKAAgDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAMG/8QAIRAAAQMDBAMAAAAAAAAAAAAAAQACAwUREgQTIVExNEH/xAAVAQEBAAAAAAAAAAAAAAAAAAADBP/EABkRAQACAwAAAAAAAAAAAAAAAAEAEQIDMf/aAAwDAQACEQMRAD8AtqJ9imRtlbE90tn5cXDSfBPY6RZyoe8wfMEUhqMgY9X2f//Z';
