export const projects = [
  {
    slug: 'transcoder',
    index: '01',
    name: 'Transcoder',
    category: 'Video infrastructure',
    domain: 'transcode.procd.cc',
    url: 'https://transcode.procd.cc/',
    repo: 'belphegor-s/video-transcoding-service',
    summary: 'Upload a video, get back adaptive HLS from 144p to 4K with AI captions in two languages. No ffmpeg, no infra to babysit.',
    description:
      'Upload a video and get back adaptive HLS from 144p to 4K, with AI captions in two languages. Each upload is handed to transcoding workers on ECS Fargate, the output lands in S3 and streams through signed CloudFront URLs. No ffmpeg on your machine, no infra to babysit, and it scales out with the queue.',
    tags: ['HLS', 'AI captions', 'Serverless', 'CDN'],
    highlights: ['Adaptive HLS ladder from 144p up to 4K', 'AI generated captions in two languages', 'Workers on ECS Fargate, triggered by Lambda', 'Private delivery through signed CloudFront URLs'],
    stack: ['Next.js', 'Express', 'ECS Fargate', 'Lambda', 'S3', 'CloudFront', 'Redis', 'ffmpeg'],
  },
  {
    slug: 'pluck',
    index: '02',
    name: 'Pluck',
    category: 'Web context for AI',
    domain: 'pluck.procd.cc',
    url: 'https://pluck.procd.cc/',
    repo: 'belphegor-s/pluck',
    summary: 'Give a model the page, not the HTML. Any URL comes back as clean markdown or JSON matching a schema you describe.',
    description:
      'Reads a URL the way a person would, running the JavaScript and skipping the cookie banner, then hands back markdown, links, a screenshot, or JSON validated against a schema you describe. Crawl a whole site, search the web with the results already read, or watch a page and get a webhook when it changes. Agents call all of it through the MCP server, and the same code runs on your own machine with no billing and no account.',
    tags: ['LLM context', 'MCP', 'Crawler', 'Open source'],
    highlights: [
      'Markdown, links, screenshots or schema-validated JSON',
      'An MCP server, so agents read the web directly',
      'Crawls, searches and change monitors on a job queue',
      'Self-hosted with one compose file, or bring your own model key',
    ],
    stack: ['TypeScript', 'Hono', 'Next.js', 'PostgreSQL', 'Redis', 'BullMQ', 'Playwright', 'Docker'],
  },
  {
    slug: 'huddle',
    index: '03',
    name: 'huddle',
    category: 'Self hosted team chat',
    domain: 'huddle.procd.cc',
    url: 'https://huddle.procd.cc/',
    repo: 'belphegor-s/huddle',
    summary: 'Team chat you run yourself. Channels, threads, files, voice notes, search and calls, in one container and a Postgres.',
    description:
      'Team chat you run yourself. Channels, threads, files, voice notes, search and calls, in one container and a Postgres. Direct messages and private channels are end to end encrypted in the browser, so the server keeps ciphertext it cannot read, even with its own database credentials.',
    tags: ['E2EE', 'WebRTC', 'Postgres', 'Self hosted'],
    highlights: ['End to end encrypted DMs and private channels', 'One container, one Postgres, one S3 compatible bucket', 'Installs from the browser with real push notifications', 'No third party requests from the browser at runtime'],
    stack: ['TypeScript', 'Postgres', 'WebRTC', 'Web Crypto', 'Web Push', 'S3', 'Docker'],
  },
  {
    slug: 'knox',
    index: '04',
    name: 'Knox',
    category: 'Browser-based VS Code',
    domain: 'knox.procd.cc',
    url: 'https://knox.procd.cc/',
    repo: 'belphegor-s/knox',
    summary: 'Real VS Code in your browser, open in one click, no install. Plus a code-execution API for running untrusted code from your own apps.',
    description:
      'Real VS Code running in an isolated Fargate container, open in one click - editor, terminal, Git, and extensions, all server-side, not emulated. Sign-in is a magic link, no password anywhere. The public demo caps sessions at 15 minutes and code-execution API calls at 2 minutes; self-hosted, none of that applies - one Docker image, no session cap, no language limit.',
    tags: ['VS Code', 'Magic link auth', 'Fargate', 'Self hosted'],
    highlights: [
      'Real code-server VS Code, not a lookalike editor',
      'A code-execution API for Python, C, C++, Java, Go, and Rust',
      'One Fargate microVM per session or execution, torn down after',
      'Self-hosted: no session cap, no language limit, no password',
    ],
    stack: ['TypeScript', 'code-server', 'ECS Fargate', 'PostgreSQL', 'Resend', 'Docker'],
  },
];
